type: s3
config: 
    bucket: prom-thanos-store
    endpoint: s3.us-east-2.amazonaws.com
    access_key: AKIAVHE5HZ6OSSODRKLK
    secret_key: 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
    encrypts: true
